export const MERGE_SORT_PSEUDO_CODE = [
  "public int[] mergeSort(int[] arr) { // Define method",
  "  if (arr.length <= 1) { // Base case: 1 element is sorted",
  "    return arr; // Return array immediately",
  "  }",
  "  int mid = arr.length / 2; // Find middle index",
  "  int[] left = mergeSort(copyOfRange(arr, 0, mid)); // Recursively sort left half",
  "  int[] right = mergeSort(copyOfRange(arr, mid, arr.length)); // Recursively sort right half",
  "  return merge(left, right); // Merge sorted halves",
  "}",
  "",
  "public int[] merge(int[] left, int[] right) { // Helper: merge two sorted arrays",
  "  int[] result = new int[left.length + right.length]; // Create result array",
  "  while (i < left.length && j < right.length) { // Loop while both have items",
  "    if (left[i] <= right[j]) { // Compare elements",
  "      result[k++] = left[i++]; // Take smaller from left",
  "    } else {",
  "      result[k++] = right[j++]; // Take smaller from right",
  "    }",
  "  }",
  "  // Copy any remaining elements",
  "  return result; // Return combined sorted array",
  "}"
];
